#pragma once

#include "types.h"

#define PIT_FREQ 1193182UL // per sec
#define MS_TO_COUNT(x) ( (uint32_t)(x) * PIT_FREQ / 1000)
#define US_TO_COUNT(x) ( (uint32_t)(x) * PIT_FREQ / 1000000)

#define PIT_PORT_CONTROL 0x43
#define PIT_PORT_COUNTER0 0x40
#define PIT_PORT_COUNTER1 0x41
#define PIT_PORT_COUNTER2 0x42

#define PIT_CONTROL_COUNTER0 0x00
#define PIT_CONTROL_COUNTER1 0x40
#define PIT_CONTROL_COUNTER2 0x80
#define PIT_CONTROL_LSBMSBRW 0x30
#define PIT_CONTROL_LATCH 0x00
#define PIT_CONTROL_MODE0 0x00
#define PIT_CONTROL_MODE2 0x04

#define PIT_CONTROL_BIN_COUNTER 0x00
#define PIT_CONTROL_BCD_COUNTER 0x01

#define PIT_COUNTER0_ONCE ( PIT_CONTROL_COUNTER0 | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE0 | PIT_CONTROL_BIN_COUNTER )
#define PIT_COUNTER0_PERI ( PIT_CONTROL_COUNTER0 | PIT_CONTROL_LSBMSBRW | PIT_CONTROL_MODE2 | PIT_CONTROL_BIN_COUNTER )
#define PIT_COUNTER0_LATCH (PIT_CONTROL_COUNTER0 | PIT_CONTROL_LATCH)

void k_init_PIT(uint16_t count, BOOL is_periodic);
uint16_t k_read_counter0(void);
void k_wait_using_direct_PIT(uint16_t count);